plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
}

group = 'co.com.screenplay.project'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

ext {
    serenityVersion = '3.9.8'
    cucumberVersion = '7.14.0'
}

dependencies {

    testImplementation "net.serenity-bdd:serenity-core:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-junit:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-cucumber:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-screenplay:$serenityVersion"
    testImplementation "net.serenity-bdd:serenity-screenplay-webdriver:$serenityVersion"

    testImplementation "io.cucumber:cucumber-java:$cucumberVersion"
    testImplementation "io.cucumber:cucumber-junit:$cucumberVersion"

    testImplementation "org.seleniumhq.selenium:selenium-java:4.18.1"
    testImplementation "junit:junit:4.13.2"
}

test {
    systemProperties System.getProperties()
}
